config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :resolutions do
    resources :updates
  end

  root to: redirect('/resolutions')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resolution.rb
# frozen_string_literal: true

class Resolution < ApplicationRecord
  validates_presence_of :title, :goal, :unit, :start_date, :end_date
  has_many :updates
  belongs_to :user

  def last_update
    updates.max_by(&:created_at)
  end

  def total_progress
    updates.sum(:progress)
  end

  def percentage_completed
    return 0 if goal.zero?

    (BigDecimal(total_progress) / BigDecimal(goal)) * 100
  end

  def complete?
    total_progress >= goal
  end
end

app/models/update.rb
# frozen_string_literal: true

class Update < ApplicationRecord
  validates_presence_of %i(date progress)
  belongs_to :resolution

  def summary
    if note.blank?
      signed_progress
    else
      "#{note} #{signed_progress}"
    end
  end

  def signed_progress
    if progress.positive? 
      "+#{progress}"
    else
      progress.to_s
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :resolutions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  private

  def set_flash(save_errors)
    flash.alert = save_errors.messages.map do |field, errors|
      "#{field.to_s.capitalize} #{errors.first}"
    end
  end
end

app/controllers/resolution/updates_controller.rb
class Resolution::UpdatesController < ApplicationController
end

app/controllers/resolutions_controller.rb
class ResolutionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @resolutions = Resolution.where(user: current_user).includes(:updates)
  end

  def new
    @resolution = Resolution.new(start_date: Date.today, end_date: Date.today.end_of_year)
  end

  def create
    resolution = Resolution.new(resolution_params.merge(user: current_user))

    if resolution.save
      flash[:success] = ["Resolution made"]
      redirect_to resolutions_url
    else
      set_flash(resolution.errors)
      redirect_to new_resolution_url
    end
      
  end

  def edit
    @resolution = Resolution.find(params[:id])
  end

  def update
    resolution = Resolution.find(params[:id])

    if resolution.update(resolution_params)
      flash[:success] = ["Resolution updated!"]
      redirect_to resolutions_url
    else
      set_flash(resolution.errors)
      redirect_to edit_resolution_url(resolution)
    end
  end

  def destroy
    resolution = Resolution.find(params[:id]).destroy
    
    flash[:success] = ["Resolution removed"]
    redirect_to resolutions_url
  end

  private

  def resolution_params
    params.require(:resolution).permit(:title, :goal, :unit, :start_date, :end_date)
  end
end

app/controllers/updates_controller.rb
# frozen_string_literal: true

class UpdatesController < ApplicationController
  attr_reader :resolution
  before_action :set_resolution,:authenticate_user!

  def index
    @updates = resolution.updates
  end
  
  def create
    update = Update.new(update_params)

    if update.save
      flash[:success] = "Resolution updated! Good work!"
      redirect_to resolutions_url
    else
      set_flash(update.errors)
      redirect_to new_resolution_update_url
    end
  end

  def new
    @update = Update.new(resolution: resolution, date: Date.today)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_resolution
    @resolution = Resolution.find(params[:resolution_id])
  end

  def update_params
    params.require(:update).permit(:date, :progress, :note).merge(
      params.permit(:resolution_id)
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:alert] %>
  <div id='flash-alert' class='error'  role='alert'>
    <% Array(flash[:alert]).each do |alert| %>
      <p><strong><%= alert %></strong></p>
    <% end %>
  </div>
<% elsif flash[:success] %>
  <div id='flash-alert'>
    <% Array(flash[:success]).each do |success| %>
      <p><strong><%= success %></strong></p>
    <% end %>
  </div>
<% end %>

<script>
  if (document.getElementById('flash-alert')) {
    setTimeout(
      () => {
        const alert = document.getElementById('flash-alert');
        alert.style.opacity = '100';

        setTimeout(() => alert.style.opacity = '0', 5000);
      },
      250
    );
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ResolutionBoard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless flash.empty? %>
      <%= render partial: "layouts/flash" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/resolutions/_form.html.erb
<% submit_url = @resolution.new_record? ? resolutions_url : resolution_url(@resolution) %>
<%= form_for(
      @resolution,
      html: { class: 'form-center' }
    ) do |form| %>
  <div class='form-row'>
    <div class='form-element large-element'>
      <label>Title</label>
      <%= form.text_field :title, placeholder: "Make 3 resolutions" %>
    </div>
  </div>
  <div class='form-row'>
    <div class='form-element'>
      <label>Goal</label>
      <%= form.text_field :goal, placeholder: 3 %>
    </div>
    <div class='form-element'>
      <label>Unit</label>
      <%= form.text_field :unit, placeholder: "Resolutions" %>
    </div>
  </div>
  <div class='form-row'>
    <div class='form-element'>
      <label>Start Date</label>
      <%= form.date_field :start_date %>
    </div>
    <div class='form-element'>
      <label>End Date</label>
      <%= form.date_field :end_date %>
    </div>
  </div>
  <div class='form-row'>
    <%= form.submit "Submit", class: "button" %>
    <%= link_to "Cancel", resolutions_url, class: "button" %>
  </div>
<% end %>

app/views/resolutions/edit.html.erb
<div class='small-page'>
  <div class='title'>
    <h1>Change Your Resolution</h1>
    <h4>How have your goals changed?</h4>
  </div>
  <div class='content'>
    <%= render "form" %>
    <div class='form-row'>
      <%= button_to "Delete", resolution_url(@resolution),
                    method: :delete, data: { confirm: "Are you sure?" }, class: "button" %>
    </div>
  </div>
</div>

app/views/resolutions/index.html.erb
<div class='title'>
  <h1> Resolution Board </h1>
  <h4> See how your goals are progressing</h4>
</div>
<div class='content'>
  <% @resolutions.each do |resolution| %>
    <div class='resolution-card'>
      <%= link_to octicon("pencil", height: 20),
                  edit_resolution_url(resolution),
                  class: 'edit-button' %>
      <div class='resolution-card-row'>
        <div class='col goal-title'><strong><%=resolution.title%></strong></div>
        <div class='progress-text'>
          <% latest_update = resolution.last_update %>
          <% unless latest_update.nil? %>
            <label class='update-label'>
              Last Updated <%= latest_update.date.to_s %>: <%= latest_update.summary %>
            </label>
          <% end %>
        </div>
      </div>
      <div class='resolution-card-row'>
        <div class='actions col'>
          <%= link_to "Add Update", new_resolution_update_url(resolution), class: "update-link" %>
        </div>
        <div class='col'>
          <div class='progress-bar'>
            <div class='completed-bar <%= 'full' if resolution.complete? %>'
                 style='width: <%= [resolution.percentage_completed, 100].min %>%'>
            </div>
            <span class='progress'>
              <%= "#{resolution.total_progress}/#{resolution.goal} #{resolution.unit}" %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <%end%>
  <% if @resolutions.empty? %>
    <div class="empty-contiainer">
      <h4>Looks like you have no resolutions yet</h4>
      <%= link_to "Make A Resolution", new_resolution_url, class: 'button add-button' %>
    </div>
  <% end %>
</div>
<div class='footer'>
  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "footer-button" %>
  <%= link_to "Make A Resolution", new_resolution_url, class: 'footer-button add-card' %>
  <%= link_to "Manage Account", edit_user_registration_path, class: "footer-button" %>
</div>

app/views/resolutions/new.html.erb
<div class='small-page'>
  <div class='title'>
    <h1>Make a Resolution</h1>
    <h4>Define a new goal</h4>
  </div>
  <div class='content'>
    <%= render "form" %>
  </div>
</div>

app/views/updates/new.html.erb
<div class='small-page'>
  <div class='title'>
    <h1>Update Your Progress!</h1>
    <h3>Goal: <%= @resolution.title %> </h3>
  </div>
  
  <div class='content'>
    <%= form_for(
          @update,
          url: resolution_updates_url(@resolution),
          method: "post",
          html: { class: 'form-center' }
        ) do |form| %>
      <div class='form-row'>
        <div class='form-element'>
          <label>Date</label>
          <%= form.date_field :date %>
        </div>
        <div class='form-element'>
          <label>Progress</label>
          <%= form.number_field :progress %> 
        </div>
        <div class='form-element'>
          <label>Note</label>
          <%= form.text_field :note, class: "wide-input" %>
        </div>
      </div>
      <div class='form-row'>
        <%= form.submit "Submit", class: "button" %>
        <%= link_to "Cancel", resolutions_url, class: "button" %>
      </div>
    <% end %>
  </div>
</div>